### ISSUE TITLE
Error while installation

### ISSUE THREAD

**Issue by ngoctranapc06** [tkikawa/WAGASCI-BabyMIND-MC#2] opened 2019-10-02 07:41 UTC
I got this error while trying to install MC package on KEKCC.
$ `git clone https://github.com/tkikawa/WAGASCI-BabyMIND-MC.git`
$ `cd WAGASCI-BabyMIND-MC`
$ `vi install.bash`
Modify line `536` leading to my working directory
`cd /home/t2k/tvngoc/tvngoc_link/WAGASCI-BabyMIND-MC`
`#cd WAGASCI-BabyMIND-MC`
$ `vi ~/.bashrc`
Comment out `cernlib 2005`. Log out and log in ssh again. cd to WAGASCI-BabyMIND-MC
$ `./install.bash`
Get error:
[error_wagasci_installation.txt](https://github.com/tkikawa/WAGASCI-BabyMIND-MC/files/3679960/error_wagasci_installation.txt)

My .bashrc
[bashrc.txt](https://github.com/tkikawa/WAGASCI-BabyMIND-MC/files/3679968/bashrc.txt)

**Comment by LastStarDust** [comment] 2019-10-02 14:14
Thank you for the very detailed bug report.
The problem is that your `.bashrc` is a mess.
The installation script assumes a "vanilla" KEKCC environment. I mean a clean` .bashrc`. In your case, there are many ROOT, GEANT4, CERNLIB etc all mixed together in the same file. My advice is, for the time being, to remove any modification that my script made to your `.bashrc`, then
```
cd ~
mv .bashrc .bashrc.backup
cp /etc/skel/.bashrc ~/.bashrc
logout
```
Then log in again and rerun the installation script as you already did.

You can revert your .bashrc back when you want to do some other analysis.

**Comment by ngoctranapc06** [comment] 2019-10-07 03:03
Thank you very much. Just one minor thing is that latest cmake version is 3.15.0, so we need to update cmake version in `install.bash`
`#CMAKEVERS="3.14.4"`
`CMAKEVERS="3.15.0"`

**Comment by LastStarDust** [comment] 2019-10-07 04:07
Thank you for the correction. I have updated the install.bash script.
Closing the issue as solved.

**Closed as completed by LastStarDust** 2019-10-07 04:07 UTC
Labels: help wanted, good first issue
